### ISSUE TITLE
iOS Code Error

### ISSUE THREAD

**Issue by andrewackerman** [rxlabz/speech_recognition#10]
On building for iOS, the code is throwing an error on line 115 in the file "SwiftSpeechRecognitionPlugin.swift":

    guard let inputNode = audioEngine.inputNode else {

> ** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET speech_recognition OF PROJECT Pods WITH CONFIGURATION Debug ===
/\<flutter-lib\>/.pub-cache/hosted/pub.dartlang.org/speech_recognition-0.2.0+1/ios/Classes/SwiftSpeechRecognitionPlugin.swift:115:11: error: initializer for conditional binding must have Optional type, not 'AVAudioInputNode'
guard let inputNode = audioEngine.inputNode else {
^

The cause seems to be that audioEngine is not an `Optional` type, and according to the [AVAudioEngine Documentation](https://developer.apple.com/documentation/avfoundation/avaudioengine?changes=_1) neither is the `inputNode` member, and without an `Optional` value, `guard` throws an error.

**Comment by zinwalin** [comment]
remove guard keyword, and make changes to like this:

let inputNode = audioEngine.inputNode

**Comment by andrewackerman** [comment]
@zinwalin I'm well aware of how to fix the issue. I posted here because it's a standing issue with the codebase that other people will also have to account for and thus should be fixed at the source. (Though judging by the fact that the last commit in this repo was over a year ago, that fix probably isn't going to happen any time soon.)
