### ISSUE TITLE
Add support to dart sdk version above 2.0.0

### ISSUE THREAD

**Issue by DineshkumarThiran** [rxlabz/speech_recognition#11]
I am getting this error while running flutter packages get.,
 
Running "flutter packages get" in  App...
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because App depends on speech_recognition >=0.2.0+1 which requires SDK version <2.0.0, version solving failed.

Can you please add support to the dart 2.1?

**Comment by gurgenDP** [comment]
Same problem. Please follow up

**Comment by dbbd59** [comment]
Same here

**Comment by OsmanBrito** [comment]
My proposal solution https://github.com/rxlabz/speech_recognition/pull/13

**Comment by rxlabz** [comment]
sorry I wasn't very active this year... it's fixed now
