### ISSUE TITLE
Dart SDK <2.0.0 required while running packages get . (pug get failed (1))

### ISSUE THREAD

**Issue by aman-malhotra-1999** [rxlabz/speech_recognition#14]
D:\Flutter\Sdk\flutter\bin\flutter.bat --no-color packages upgrade
**Running "flutter packages upgrade" in music_player...
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.**
**Because music_player depends on speech_recognition any which requires SDK version >=1.23.0 <2.0.0, version solving failed.
pub upgrade failed (1)**

**Comment by jacqueslewis** [comment]
I have the same issue

```Running "flutter packages upgrade" in tablet_interactive...     
The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

Because tablet_interactive depends on speech_recognition >=0.2.0+1 which requires SDK version <2.0.0, version solving failed.

pub upgrade failed (1)
```

**Comment by rxlabz** [comment]
sorry for the delay, but it's fixed now.
