### ISSUE TITLE
Volume decreases after invoking speech recognition on IOS.

### ISSUE THREAD

**Issue by daothan1211** [rxlabz/speech_recognition#62]
Hi team.
I’m using speech_recognition 0.3.0+1 with flutter. I’ve tested with simulator IOS, it worked properly.
But when I build and test on a real device (iPhone 7 plus), have a problem, when the first time I start the app, volume work as normal, but whenever I invoke a speech recognition, the overall volume of the app decreases.
I tried to fix follow [guide](https://github.com/nmfisher/speech_recognition/commit/48d4cccadd5a9381bc7df49f7ab63c792419f40f). But it still not works.

Please help me to find the solution for this, thanks team

**Comment by crizant** [comment]
Because the `AVAudioSession` is set to `measurement`.

You may:
1. In the swift code which plays audio, set the `AVAudioSession` mode back to `default`
2. Clone this repo, and remove line 112:
```
try audioSession.setMode(AVAudioSession.Mode.measurement)
```
in SwiftSpeechRecognitionPlugin.swift.

**Comment by daothan1211** [comment]
Thanks for your response,
And, do we still need use Swift 4.2?

**Comment by crizant** [comment]
@daothan1211 Yes in my case.

**Comment by daothan1211** [comment]
Thanks for your support, I will try and hope it will work properly.

**Comment by daothan1211** [comment]
@crizant Thanks so much, It works.
And it can work with Swift 5.
