### ISSUE TITLE
onError: 5

### ISSUE THREAD

**Issue by wish4129** [rxlabz/speech_recognition#65]
![Screenshot_1](https://user-images.githubusercontent.com/8197678/67095822-725ecc00-f1e9-11e9-926a-658d6f9047c6.png)

Anyone had this problem hitting unknown Error 5? it happens when I try to use the speechRecognition more than a few times.

**Comment by andrezanna** [comment]
https://developer.android.com/reference/android/speech/SpeechRecognizer
you can look here for details

**Comment by wish4129** [comment]
turn out it's my api not responding properly cause the recognizer not working properly

**Comment by ramsham2411** [comment]
@wish4129 Did you fixed it somehow. any solution would be appreciated.
Thanks.

**Comment by wish4129** [comment]
@ramsham2411 for my problems, it's due to my button's problem, to fix this, you need to either reset/reinitiate the speech_recognition or set it to the ready state will be fine.
