### ISSUE TITLE
Error on Android Pie

### ISSUE THREAD

**Issue by toshiossada** [rxlabz/speech_recognition#66]
I tried to run example  on android Pie API 28 but when I clicked to record I got following error

I/flutter (13784): _platformCallHandler call speech.onSpeechAvailability false
I/flutter (13784): _platformCallHandler call speech.onError 2
I/flutter (13784): Unknowm method speech.onError

**Comment by Harishpenta** [comment]
i am also facing same issue.

**Comment by toshiossada** [comment]
I tried to run on device with Android Q (Google Pixel) and works very well, i got the error only at the emulator
