### ISSUE TITLE
SpeechRecognitionPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by toshiossada** [rxlabz/speech_recognition#67]
When I Run app, I got a note
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\speech_recognition-0.3.0+1\android\src\main\java\bz\rxla\flutter\speechrecognition\SpeechRecognitionPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Ccastillo06** [comment]
@toshiossada do you know if there's any solution for this yet? Doesn't seem to break my build or anything but is not nice having this warning around.

**Comment by toshiossada** [comment]
@Ccastillo06  I dont thinkso, I think that package are not be supported anymore, do you know any other package to speech_reognition?
