### ISSUE TITLE
Speech recognition only works once

### ISSUE THREAD

**Issue by mploigt** [rxlabz/speech_recognition#75]
If you do a recognition, click on stop and try again immediately, no text will be recognised. Only if you wait for approx 30 seconds, recognition will work again.

**Comment by ramsham2411** [comment]
Did you get solution for this one?

**Comment by mploigt** [comment]
Apparently this was a bug in iOS 13.2. In 13.3. it works again.

**Comment by ramsham2411** [comment]
I am actually a newbie I just updated the device, but still getting the same error. Do I have to update the flutter as well.
